
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Research Tool")

window.geometry("800x500")
window.configure(bg = "#EEEEEE")


canvas = Canvas(
    window,
    bg = "#EEEEEE",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    400.0,
    500.0,
    fill="#00ADB5",
    outline="")

canvas.create_text(
    7.0,
    481.0,
    anchor="nw",
    text="©  (2022) Christoph Beckmann",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    58.0,
    408.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    58.0,
    341.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    58.0,
    274.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    58.0,
    208.0,
    image=image_image_4
)

canvas.create_text(
    85.0,
    392.0,
    anchor="nw",
    text="Further Research",
    fill="#FFFFFF",
    font=("Roboto", 24 * -1)
)

canvas.create_text(
    85.0,
    325.0,
    anchor="nw",
    text="Analyze Keywords",
    fill="#FFFFFF",
    font=("Roboto", 24 * -1)
)

canvas.create_text(
    85.0,
    258.0,
    anchor="nw",
    text="Identify Keywords",
    fill="#FFFFFF",
    font=("Roboto", 24 * -1)
)

canvas.create_text(
    85.0,
    194.0,
    anchor="nw",
    text="Summarize Text",
    fill="#FFFFFF",
    font=("Roboto", 24 * -1)
)

canvas.create_text(
    50.0,
    56.0,
    anchor="nw",
    text="Research Tool",
    fill="#EEEEEE",
    font=("Roboto", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=500.0,
    y=379.0,
    width=200.0,
    height=58.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=500.0,
    y=288.0,
    width=200.0,
    height=58.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=500.0,
    y=197.0,
    width=200.0,
    height=58.0
)

canvas.create_text(
    415.0,
    66.0,
    anchor="nw",
    text="What should be done?",
    fill="#222831",
    font=("Roboto", 36 * -1)
)
window.resizable(False, False)
window.mainloop()
